eventHub:
  namespace: your namespace here
  eventHubName: your event hub name
  sharedAccessKey: your event hub shared access key
  sharedAccessKeyName: your shared access key name
  maxBatchSize: 3
  storage:
    consumerGroupName: your consumer group
    storageConnectionString: your storage connection string
    storageContainerName: your storage container name
    hostNamePrefix: your host name prefix

