eventHub:
  connectionString: 'connections string here'
  name: 'event hub name here'
  storage:
    consumerGroupName: $Default
    storageConnectionString: 'storage connection string here'
    storageContainerName: 'storage container name here'
    hostNamePrefix: f1534aa5-262b-4c6b-a9f8-fd5af544f85b
